name: CodeQL Scan and Create Issues

on:
  schedule:
    - cron: "0 3 1 * *" # 毎月1日の午前3時に実行
  workflow_dispatch:

jobs:
  analyze:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
      issues: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'typescript' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      # スキャンの実行時間が長いので、スキャンしない（本番ではスキャンするようにコメントアウトをはずす！）
      #- name: Perform CodeQL Analysis
      #  uses: github/codeql-action/analyze@v3

      - name: Create Issues from CodeQL Alerts
        uses: actions/github-script@v7
        with:
          script: |
            const { data: alerts } = await github.request(
              "GET /repos/${{ github.repository }}/code-scanning/alerts",
              { state: "open" }
            );

            for (const alert of alerts) {
              const ruleId = alert.rule.id;
              const file = alert.most_recent_instance?.location?.path || "unknown file";
              const issueTitle = `CodeQL Alert: ${ruleId} in ${file}`;

              // 既存のIssueを検索
              const { data: issues } = await github.rest.issues.listForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: "open"
              });

              const exists = issues.some(issue => issue.title === issueTitle);
              if (exists) continue;

              // Issue本文を作成（Copilot向け指示を追加）
              const body = "**Rule**: " + ruleId + "\n**Severity**: " + alert.rule.severity + "\n**File**: " + file + "\n**URL**: " + alert.html_url + "\n\n**Details:**\n" + alert.rule.description + "\n\n@github-copilot please suggest a fix\ncc @ikeikejunjun";

              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: issueTitle,
                body: body,
                assignees: ["ikeikejunjun", "copilot-swe-agent"]
              });
            }

      - name: Assign Copilot via GraphQL
        run: |
          ISSUE_ID=$(curl -s -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"query":"query { repository(owner:\"YOUR_ORG\", name:\"YOUR_REPO\") { issue(number: ISSUE_NUMBER) { id }}}"}' \
            https://api.github.com/graphql | jq -r '.data.repository.issue.id')

          echo "Issue ID: $ISSUE_ID"

          # Copilot の user ID を使う必要がある
          COPILOT_ID=$(curl -s -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"query":"query { user(login:\"copilot\") { id }}"}' \
            https://api.github.com/graphql | jq -r '.data.user.id')

          echo "Copilot ID: $COPILOT_ID"

          # issue に Copilot をアサイン
          curl -s -X POST \
            -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"query\":\"mutation { updateIssue(input: {issueId: \\\"$ISSUE_ID\\\", assigneeIds: [\\\"$COPILOT_ID\\\"]}) { issue { number assignees(first:5) { nodes { login } } } }}\"}" \
            https://api.github.com/graphql
